#!/usr/bin/env python3
"""生成代码解释Word文档"""
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn


def set_chinese_font(run, font_name='微软雅黑', size=10.5, bold=False, color=None):
    """设置中文字体"""
    run.font.name = font_name
    run._element.rPr.rFonts.set(qn('w:eastAsia'), font_name)
    run.font.size = Pt(size)
    run.font.bold = bold
    if color:
        run.font.color.rgb = RGBColor(*color)


def add_code_line(doc, line_num, code, explanation):
    """添加代码行解释"""
    p = doc.add_paragraph()
    # 行号
    run1 = p.add_run(f"{line_num:3d} | ")
    set_chinese_font(run1, size=9, color=(128, 128, 128))
    # 代码
    run2 = p.add_run(code[:60])
    set_chinese_font(run2, font_name='Consolas', size=9, color=(0, 0, 139))
    # 解释
    if explanation:
        run3 = p.add_run(f"  ← {explanation}")
        set_chinese_font(run3, size=9, color=(0, 128, 0))


def add_file_section(doc, filename):
    """添加文件分区标题"""
    p = doc.add_heading(f'📄 {filename}', level=2)
    for run in p.runs:
        set_chinese_font(run, size=14, bold=True, color=(0, 51, 102))


def create_explanation_doc():
    """创建完整的代码解释文档"""
    doc = Document()
    
    # 设置文档标题
    title = doc.add_heading('待办清单应用 - 代码详解', 0)
    for run in title.runs:
        set_chinese_font(run, size=20, bold=True, color=(0, 51, 102))
    
    # 添加说明
    intro = doc.add_paragraph()
    intro_text = '''本文档逐行解释了待办清单桌面应用的每一行代码，帮助你理解程序的工作原理。

技术栈：Python 3 + tkinter (GUI) + sqlite3 (数据库)
项目结构：模块化设计，分为配置、数据库、GUI三个主要部分'''
    run = intro.add_run(intro_text)
    set_chinese_font(run, size=10.5)
    
    doc.add_page_break()
    
    # ==================== 配置文件 ====================
    add_file_section(doc, 'config.py - 应用配置文件')
    
    doc.add_paragraph('【模块说明】存放应用程序的全局配置参数，如数据库路径、窗口大小、优先级定义等。使用配置文件便于统一修改，避免硬编码。')
    
    add_code_line(doc, 1, '"""应用配置"""', '模块文档字符串（docstring），说明该文件用途')
    add_code_line(doc, 2, 'import os', '导入os模块，用于处理文件路径等操作系统相关功能')
    add_code_line(doc, 3, '', '')
    add_code_line(doc, 4, '# 数据库配置', '注释：下面定义数据库相关的配置项')
    add_code_line(doc, 5, "DB_PATH = os.path.join(os.path.dirname(__file__), 'todo.db')", '定义数据库文件路径：使用os.path.join拼接路径，确保跨平台兼容（Windows用\\，Linux/Mac用/）；os.path.dirname(__file__)获取当前文件所在目录')
    add_code_line(doc, 6, "DATABASE_URL = f'sqlite:///{DB_PATH}'", '定义数据库URL，使用f-string格式化字符串，sqlite:///是SQLite的连接协议前缀')
    add_code_line(doc, 7, '', '')
    add_code_line(doc, 8, '# GUI 配置', '注释：图形界面窗口的配置参数')
    add_code_line(doc, 9, "WINDOW_TITLE = '待办清单'", '定义主窗口标题栏显示的文字')
    add_code_line(doc, 10, 'WINDOW_WIDTH = 900', '定义窗口宽度为900像素')
    add_code_line(doc, 11, 'WINDOW_HEIGHT = 600', '定义窗口高度为600像素')
    add_code_line(doc, 12, '', '')
    add_code_line(doc, 13, '# 优先级配置', '注释：任务优先级的常量定义')
    add_code_line(doc, 14, 'PRIORITY_HIGH = 1', '定义高优先级对应的数值1（数值越小优先级越高）')
    add_code_line(doc, 15, 'PRIORITY_MEDIUM = 2', '定义中优先级对应的数值2')
    add_code_line(doc, 16, 'PRIORITY_LOW = 3', '定义低优先级对应的数值3')
    add_code_line(doc, 17, '', '')
    add_code_line(doc, 18, 'PRIORITY_NAMES = {', '定义优先级数值到中文名称的映射字典（dict）')
    add_code_line(doc, 19, "    PRIORITY_HIGH: '高',", '键1对应值"高"')
    add_code_line(doc, 20, "    PRIORITY_MEDIUM: '中',", '键2对应值"中"')
    add_code_line(doc, 21, "    PRIORITY_LOW: '低'", '键3对应值"低"')
    add_code_line(doc, 22, '}', '字典定义结束')
    add_code_line(doc, 23, '', '')
    add_code_line(doc, 24, 'PRIORITY_COLORS = {', '定义优先级对应的颜色字典（用于GUI显示）')
    add_code_line(doc, 25, "    PRIORITY_HIGH: '#FF4444',", '高优先级使用红色（#FF4444是十六进制颜色码）')
    add_code_line(doc, 26, "    PRIORITY_MEDIUM: '#FFAA00',", '中优先级使用橙色')
    add_code_line(doc, 27, "    PRIORITY_LOW: '#44AA44'", '低优先级使用绿色')
    add_code_line(doc, 28, '}', '字典定义结束')
    add_code_line(doc, 29, '', '')
    add_code_line(doc, 30, '# 默认分类', '注释：首次运行应用时自动创建的默认分类')
    add_code_line(doc, 31, 'DEFAULT_CATEGORIES = [', '定义列表（list），包含多个字典，每个字典代表一个分类')
    add_code_line(doc, 32, "    {'name': '工作', 'color': '#4A90D9'},", '第一个分类：工作，蓝色')
    add_code_line(doc, 33, "    {'name': '个人', 'color': '#9B59B6'},", '第二个分类：个人，紫色')
    add_code_line(doc, 34, "    {'name': '学习', 'color': '#27AE60'},", '第三个分类：学习，绿色')
    add_code_line(doc, 35, "    {'name': '购物', 'color': '#E67E22'},", '第四个分类：购物，橙色')
    add_code_line(doc, 36, ']', '列表定义结束')
    
    doc.add_page_break()
    
    # ==================== 主入口 ====================
    add_file_section(doc, 'main.py - 程序入口文件')
    
    doc.add_paragraph('【模块说明】整个应用的启动入口，负责初始化并运行主窗口。这是Python程序的标准写法。')
    
    add_code_line(doc, 1, '#!/usr/bin/env python3', 'Shebang行：告诉系统使用python3解释器执行此脚本（主要在Linux/Mac上有用）')
    add_code_line(doc, 2, '"""', '多行文档字符串开始')
    add_code_line(doc, 3, '待办清单桌面应用', '应用名称说明')
    add_code_line(doc, 4, '使用 Python + tkinter + SQLite 实现', '技术栈说明')
    add_code_line(doc, 5, '"""', '文档字符串结束')
    add_code_line(doc, 6, 'import sys', '导入sys模块，用于访问系统相关参数和函数')
    add_code_line(doc, 7, 'import os', '导入os模块，用于路径处理')
    add_code_line(doc, 8, '', '')
    add_code_line(doc, 9, '# 确保可以导入本地模块', '注释：解决导入路径问题')
    add_code_line(doc, 10, 'sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))', '将当前文件所在目录添加到Python模块搜索路径的最前面，确保能导入同目录下的其他模块')
    add_code_line(doc, 11, '', '')
    add_code_line(doc, 12, 'from gui import MainWindow', '从gui包中导入MainWindow类')
    add_code_line(doc, 13, '', '')
    add_code_line(doc, 14, '', '')
    add_code_line(doc, 15, 'def main():', '定义主函数main()')
    add_code_line(doc, 16, '    """程序入口"""', '函数文档字符串')
    add_code_line(doc, 17, '    app = MainWindow()', '创建MainWindow类的实例，初始化主窗口')
    add_code_line(doc, 18, '    app.run()', '调用run()方法启动应用程序的主循环')
    add_code_line(doc, 19, '', '')
    add_code_line(doc, 20, '', '')
    add_code_line(doc, 21, "if __name__ == '__main__':", 'Python惯用法：检查是否直接运行此文件（而非作为模块导入）')
    add_code_line(doc, 22, '    main()', '如果是直接运行，则调用main()函数启动程序')
    
    doc.add_page_break()
    
    # ==================== requirements.txt ====================
    add_file_section(doc, 'requirements.txt - 依赖说明文件')
    
    doc.add_paragraph('【模块说明】列出项目依赖的第三方库。本项目仅使用Python标准库，无需额外安装。')
    
    add_code_line(doc, 1, '# 本项目只使用 Python 内置模块，无需额外依赖', '注释说明')
    add_code_line(doc, 2, '# - tkinter (GUI)', '注释：GUI框架是Python内置的')
    add_code_line(doc, 3, '# - sqlite3 (数据库)', '注释：数据库模块也是Python内置的')
    
    doc.add_page_break()
    
    # ==================== 数据模型 ====================
    add_file_section(doc, 'database/models.py - 数据模型定义')
    
    doc.add_paragraph('【模块说明】定义数据库表对应的数据结构（模型类）。使用Python的@dataclass装饰器简化类的定义。这是ORM（对象关系映射）的基础概念。')
    
    add_code_line(doc, 1, '"""数据模型"""', '模块文档字符串')
    add_code_line(doc, 2, 'from dataclasses import dataclass', '从dataclasses模块导入dataclass装饰器')
    add_code_line(doc, 3, 'from datetime import datetime', '从datetime模块导入datetime类，用于处理日期时间')
    add_code_line(doc, 4, 'from typing import Optional', '从typing模块导入Optional类型，用于表示可选（可为None）的类型')
    add_code_line(doc, 5, '', '')
    add_code_line(doc, 6, '', '')
    add_code_line(doc, 7, '@dataclass', '装饰器：自动生成__init__、__repr__等方法，简化类定义')
    add_code_line(doc, 8, 'class Category:', '定义Category（分类）类')
    add_code_line(doc, 9, '    """任务分类模型"""', '类文档字符串')
    add_code_line(doc, 10, '    id: int', '分类ID，整数类型，数据库主键')
    add_code_line(doc, 11, '    name: str', '分类名称，字符串类型')
    add_code_line(doc, 12, "    color: str = '#4A90D9'", '分类颜色，字符串类型，默认值为蓝色')
    add_code_line(doc, 13, '    created_at: Optional[datetime] = None', '创建时间，Optional表示可为None，默认值为None')
    add_code_line(doc, 14, '    ', '')
    add_code_line(doc, 15, '    def to_dict(self):', '定义实例方法：将对象转换为字典')
    add_code_line(doc, 16, '        return {', '返回字典')
    add_code_line(doc, 17, "            'id': self.id,", '字典键id对应self.id')
    add_code_line(doc, 18, "            'name': self.name,", '字典键name对应self.name')
    add_code_line(doc, 19, "            'color': self.color,", '字典键color对应self.color')
    add_code_line(doc, 20, '            self.created_at.isoformat() if self.created_at else None', '如果created_at存在则转为ISO格式字符串，否则为None')
    add_code_line(doc, 21, '        }', '字典结束')
    add_code_line(doc, 22, '', '')
    add_code_line(doc, 23, '', '')
    add_code_line(doc, 24, '@dataclass', '再次使用dataclass装饰器')
    add_code_line(doc, 25, 'class Todo:', '定义Todo（待办事项）类')
    add_code_line(doc, 26, '    """待办任务模型"""', '类文档字符串')
    add_code_line(doc, 27, '    id: int', '任务ID，主键')
    add_code_line(doc, 28, '    title: str', '任务标题')
    add_code_line(doc, 29, "    description: str = ''", '任务描述，默认空字符串')
    add_code_line(doc, 30, '    priority: int = 2', '优先级，默认2（中优先级）')
    add_code_line(doc, 31, '    completed: bool = False', '是否完成，布尔值，默认False')
    add_code_line(doc, 32, '    due_date: Optional[datetime] = None', '截止日期')
    add_code_line(doc, 33, '    created_at: Optional[datetime] = None', '创建时间')
    add_code_line(doc, 34, '    updated_at: Optional[datetime] = None', '更新时间')
    add_code_line(doc, 35, '    category_id: Optional[int] = None', '所属分类ID')
    add_code_line(doc, 36, '    category_name: Optional[str] = None', '所属分类名称（用于关联查询时显示）')
    add_code_line(doc, 37, '    category_color: Optional[str] = None', '所属分类颜色（用于关联查询时显示）')
    add_code_line(doc, 38, '    ', '')
    add_code_line(doc, 39, '    def to_dict(self):', '转换为字典的方法')
    add_code_line(doc, 40, '        return {', '返回字典')
    add_code_line(doc, 41, "            'id': self.id,", '')
    add_code_line(doc, 42, "            'title': self.title,", '')
    add_code_line(doc, 43, "            'description': self.description,", '')
    add_code_line(doc, 44, "            'priority': self.priority,", '')
    add_code_line(doc, 45, "            'completed': self.completed,", '')
    add_code_line(doc, 46, "            'due_date': self.due_date.isoformat() if self.due_date else None,", '')
    add_code_line(doc, 47, "            'created_at': self.created_at.isoformat() if self.created_at else None,", '')
    add_code_line(doc, 48, "            'updated_at': self.updated_at.isoformat() if self.updated_at else None,", '')
    add_code_line(doc, 49, "            'category_id': self.category_id,", '')
    add_code_line(doc, 50, "            'category_name': self.category_name,", '')
    add_code_line(doc, 51, "            'category_color': self.category_color", '')
    add_code_line(doc, 52, '        }', '字典结束')
    add_code_line(doc, 53, '', '')
    
    doc.add_page_break()
    
    # ==================== 数据库管理器 ====================
    add_file_section(doc, 'database/db_manager.py - 数据库管理器')
    
    doc.add_paragraph('【模块说明】封装所有数据库操作，提供增删改查接口。使用上下文管理器确保数据库连接正确关闭。这是DAO（数据访问对象）模式的应用。')
    
    add_code_line(doc, 1, '"""数据库管理器 - 使用 sqlite3"""', '模块说明')
    add_code_line(doc, 2, 'import sqlite3', '导入SQLite数据库模块')
    add_code_line(doc, 3, 'from datetime import datetime', '导入datetime')
    add_code_line(doc, 4, 'from typing import List, Optional', '导入类型提示：List列表、Optional可选类型')
    add_code_line(doc, 5, 'from contextlib import contextmanager', '导入上下文管理器装饰器，用于简化资源管理')
    add_code_line(doc, 6, '', '')
    add_code_line(doc, 7, 'from .models import Category, Todo', '从同级models模块导入Category和Todo类')
    add_code_line(doc, 8, 'from config import DB_PATH, DEFAULT_CATEGORIES', '从config导入配置')
    add_code_line(doc, 9, '', '')
    add_code_line(doc, 10, '', '')
    add_code_line(doc, 11, 'class DBManager:', '定义数据库管理器类')
    add_code_line(doc, 12, '    """数据库管理类"""', '类文档字符串')
    add_code_line(doc, 13, '    ', '')
    add_code_line(doc, 14, '    def __init__(self):', '构造方法')
    add_code_line(doc, 15, '        self.db_path = DB_PATH', '将数据库路径保存为实例属性')
    add_code_line(doc, 16, '        self.init_database()', '调用初始化方法创建表结构')
    add_code_line(doc, 17, '    ', '')
    add_code_line(doc, 18, '    @contextmanager', '装饰器：将下面的方法转为上下文管理器')
    add_code_line(doc, 19, '    def get_connection(self):', '定义获取连接的方法')
    add_code_line(doc, 20, '        """获取数据库连接的上下文管理器"""', '')
    add_code_line(doc, 21, '        conn = sqlite3.connect(self.db_path)', '建立数据库连接')
    add_code_line(doc, 22, '        conn.row_factory = sqlite3.Row', '设置行工厂：使查询结果可以通过列名访问')
    add_code_line(doc, 23, '        try:', 'try块开始')
    add_code_line(doc, 24, '            yield conn', 'yield交出连接，供with语句使用')
    add_code_line(doc, 25, '        finally:', 'finally块：无论是否发生异常都会执行')
    add_code_line(doc, 26, '            conn.close()', '关闭连接，释放资源')
    add_code_line(doc, 27, '    ', '')
    add_code_line(doc, 28, '    def init_database(self):', '初始化数据库方法')
    add_code_line(doc, 29, '        """初始化数据库，创建表和默认数据"""', '')
    add_code_line(doc, 30, '        with self.get_connection() as conn:', '使用上下文管理器获取连接')
    add_code_line(doc, 31, '            cursor = conn.cursor()', '创建游标对象，用于执行SQL')
    add_code_line(doc, 32, '            ', '')
    add_code_line(doc, 33, '            # 创建分类表', '注释')
    add_code_line(doc, 34, "            cursor.execute('''", '执行SQL：创建categories表')
    add_code_line(doc, 35, '                CREATE TABLE IF NOT EXISTS categories (', 'IF NOT EXISTS：如果表不存在才创建')
    add_code_line(doc, 36, '                    id INTEGER PRIMARY KEY AUTOINCREMENT,', 'id字段：整数、主键、自增')
    add_code_line(doc, 37, '                    name TEXT NOT NULL UNIQUE,', 'name字段：文本、非空、唯一')
    add_code_line(doc, 38, "                    color TEXT DEFAULT '#4A90D9',", 'color字段：文本、默认蓝色')
    add_code_line(doc, 39, '                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP', '创建时间戳，默认当前时间')
    add_code_line(doc, 40, '                )', '')
    add_code_line(doc, 41, "            ''')", '')
    add_code_line(doc, 42, '            ', '')
    add_code_line(doc, 43, '            # 创建待办事项表', '注释')
    add_code_line(doc, 44, "            cursor.execute('''", '执行SQL：创建todos表')
    add_code_line(doc, 45, '                CREATE TABLE IF NOT EXISTS todos (', '')
    add_code_line(doc, 46, '                    id INTEGER PRIMARY KEY AUTOINCREMENT,', '')
    add_code_line(doc, 47, '                    title TEXT NOT NULL,', '标题：非空')
    add_code_line(doc, 48, "                    description TEXT DEFAULT '',", '描述：默认空字符串')
    add_code_line(doc, 49, '                    priority INTEGER DEFAULT 2,', '优先级：默认2（中）')
    add_code_line(doc, 50, '                    completed BOOLEAN DEFAULT 0,', '完成状态：默认0（未完成）')
    add_code_line(doc, 51, '                    due_date TIMESTAMP,', '截止日期：可为空')
    add_code_line(doc, 52, '                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,', '创建时间')
    add_code_line(doc, 53, '                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,', '更新时间')
    add_code_line(doc, 54, '                    category_id INTEGER,', '分类ID：外键')
    add_code_line(doc, 55, '                    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL', '外键约束：关联categories表，删除分类时设为NULL')
    add_code_line(doc, 56, '                )', '')
    add_code_line(doc, 57, "            ''')", '')
    add_code_line(doc, 58, '            ', '')
    add_code_line(doc, 59, '            conn.commit()', '提交事务，保存更改')
    add_code_line(doc, 60, '            ', '')
    add_code_line(doc, 61, '            # 检查是否需要插入默认分类', '注释')
    add_code_line(doc, 62, '            cursor.execute(\'SELECT COUNT(*) FROM categories\')', '查询分类表记录数')
    add_code_line(doc, 63, '            if cursor.fetchone()[0] == 0:', '如果没有分类')
    add_code_line(doc, 64, '                for cat_data in DEFAULT_CATEGORIES:', '遍历默认分类列表')
    add_code_line(doc, 65, '                    cursor.execute(', '执行插入SQL')
    add_code_line(doc, 66, "                        'INSERT INTO categories (name, color) VALUES (?, ?)',", '参数化查询，?是占位符')
    add_code_line(doc, 67, '                        (cat_data[\'name\'], cat_data[\'color\'])', '传入实际参数')
    add_code_line(doc, 68, '                    )', '')
    add_code_line(doc, 69, '                conn.commit()', '提交插入操作')
    
    doc.add_page_break()
    
    # 续 db_manager.py
    add_file_section(doc, 'database/db_manager.py - 数据转换方法')
    
    add_code_line(doc, 71, '    def _row_to_category(self, row) -> Category:', '私有方法：将数据库行转换为Category对象')
    add_code_line(doc, 72, '        """将数据库行转换为 Category 对象"""', '')
    add_code_line(doc, 73, '        return Category(', '返回Category实例')
    add_code_line(doc, 74, "            id=row['id'],", '从row中通过列名获取id')
    add_code_line(doc, 75, "            name=row['name'],", '获取name')
    add_code_line(doc, 76, "            color=row['color'],", '获取color')
    add_code_line(doc, 77, '            created_at=datetime.fromisoformat(row[\'created_at\']) if row[\'created_at\'] else None', '将ISO格式字符串转为datetime对象')
    add_code_line(doc, 78, '        )', '')
    add_code_line(doc, 79, '    ', '')
    add_code_line(doc, 80, '    def _row_to_todo(self, row) -> Todo:', '私有方法：将数据库行转换为Todo对象')
    add_code_line(doc, 81, '        """将数据库行转换为 Todo 对象"""', '')
    add_code_line(doc, 82, '        return Todo(', '返回Todo实例')
    add_code_line(doc, 83, "            id=row['id'],", '')
    add_code_line(doc, 84, "            title=row['title'],", '')
    add_code_line(doc, 85, "            description=row['description'] or '',", '如果description为None则用空字符串')
    add_code_line(doc, 86, "            priority=row['priority'],", '')
    add_code_line(doc, 87, '            completed=bool(row[\'completed\']),', '转为布尔值')
    add_code_line(doc, 88, '            due_date=datetime.fromisoformat(row[\'due_date\']) if row[\'due_date\'] else None,', '')
    add_code_line(doc, 89, '            created_at=datetime.fromisoformat(row[\'created_at\']) if row[\'created_at\'] else None,', '')
    add_code_line(doc, 90, '            updated_at=datetime.fromisoformat(row[\'updated_at\']) if row[\'updated_at\'] else None,', '')
    add_code_line(doc, 91, "            category_id=row['category_id'],", '')
    add_code_line(doc, 92, "            category_name=row['category_name'] if 'category_name' in row.keys() else None,", '检查是否存在该列（JOIN查询时才有）')
    add_code_line(doc, 93, "            category_color=row['category_color'] if 'category_color' in row.keys() else None", '')
    add_code_line(doc, 94, '        )', '')
    add_code_line(doc, 95, '    ', '')
    add_code_line(doc, 96, '    # ========== 分类操作 ==========', '注释：分类相关的CRUD操作')
    add_code_line(doc, 97, '    ', '')
    add_code_line(doc, 98, '    def get_all_categories(self) -> List[Category]:', '获取所有分类')
    add_code_line(doc, 99, '        """获取所有分类"""', '')
    add_code_line(doc, 100, '        with self.get_connection() as conn:', '使用上下文管理器')
    add_code_line(doc, 101, '            cursor = conn.cursor()', '')
    add_code_line(doc, 102, '            cursor.execute(\'SELECT * FROM categories ORDER BY name\')', '查询所有分类，按名称排序')
    add_code_line(doc, 103, '            return [self._row_to_category(row) for row in cursor.fetchall()]', '列表推导式：将每行转为Category对象')
    add_code_line(doc, 104, '    ', '')
    add_code_line(doc, 105, '    def get_category_by_id(self, category_id: int) -> Optional[Category]:', '根据ID获取分类')
    add_code_line(doc, 106, '        """根据ID获取分类"""', '')
    add_code_line(doc, 107, '        with self.get_connection() as conn:', '')
    add_code_line(doc, 108, '            cursor = conn.cursor()', '')
    add_code_line(doc, 109, "            cursor.execute('SELECT * FROM categories WHERE id = ?', (category_id,))", '参数化查询防止SQL注入')
    add_code_line(doc, 110, '            row = cursor.fetchone()', '获取一行结果')
    add_code_line(doc, 111, '            return self._row_to_category(row) if row else None', '有数据则转换，否则返回None')
    add_code_line(doc, 112, '    ', '')
    add_code_line(doc, 113, "    def add_category(self, name: str, color: str = '#4A90D9') -> Category:", '添加分类')
    add_code_line(doc, 114, '        """添加新分类"""', '')
    add_code_line(doc, 115, '        with self.get_connection() as conn:', '')
    add_code_line(doc, 116, '            cursor = conn.cursor()', '')
    add_code_line(doc, 117, '            cursor.execute(', '')
    add_code_line(doc, 118, "                'INSERT INTO categories (name, color) VALUES (?, ?)',", '')
    add_code_line(doc, 119, '                (name, color)', '')
    add_code_line(doc, 120, '            )', '')
    add_code_line(doc, 121, '            conn.commit()', '')
    add_code_line(doc, 122, '            category_id = cursor.lastrowid', '获取刚插入的记录ID')
    add_code_line(doc, 123, '            return self.get_category_by_id(category_id)', '返回完整的Category对象')
    add_code_line(doc, 124, '    ', '')
    add_code_line(doc, 125, '    def update_category(self, category_id: int, name: str = None, color: str = None) -> bool:', '更新分类')
    add_code_line(doc, 126, '        """更新分类"""', '')
    add_code_line(doc, 127, '        with self.get_connection() as conn:', '')
    add_code_line(doc, 128, '            cursor = conn.cursor()', '')
    add_code_line(doc, 129, '            ', '')
    add_code_line(doc, 130, '            if name and color:', '如果同时更新名称和颜色')
    add_code_line(doc, 131, '                cursor.execute(', '')
    add_code_line(doc, 132, "                    'UPDATE categories SET name = ?, color = ? WHERE id = ?',", '')
    add_code_line(doc, 133, '                    (name, color, category_id)', '')
    add_code_line(doc, 134, '                )', '')
    add_code_line(doc, 135, '            elif name:', '如果只更新名称')
    add_code_line(doc, 136, '                cursor.execute(', '')
    add_code_line(doc, 137, "                    'UPDATE categories SET name = ? WHERE id = ?',", '')
    add_code_line(doc, 138, '                    (name, category_id)', '')
    add_code_line(doc, 139, '                )', '')
    add_code_line(doc, 140, '            elif color:', '如果只更新颜色')
    add_code_line(doc, 141, '                cursor.execute(', '')
    add_code_line(doc, 142, "                    'UPDATE categories SET color = ? WHERE id = ?',", '')
    add_code_line(doc, 143, '                    (color, category_id)', '')
    add_code_line(doc, 144, '                )', '')
    add_code_line(doc, 145, '            else:', '如果都没提供')
    add_code_line(doc, 146, '                return False', '返回失败')
    add_code_line(doc, 147, '            ', '')
    add_code_line(doc, 148, '            conn.commit()', '')
    add_code_line(doc, 149, '            return cursor.rowcount > 0', 'rowcount返回受影响的行数，大于0表示更新成功')
    add_code_line(doc, 150, '    ', '')
    add_code_line(doc, 151, '    def delete_category(self, category_id: int) -> bool:', '删除分类')
    add_code_line(doc, 152, '        """删除分类"""', '')
    add_code_line(doc, 153, '        with self.get_connection() as conn:', '')
    add_code_line(doc, 154, "            cursor.execute('DELETE FROM categories WHERE id = ?', (category_id,))", '')
    add_code_line(doc, 155, '            conn.commit()', '')
    add_code_line(doc, 156, '            return cursor.rowcount > 0', '')
    
    doc.add_page_break()
    
    add_file_section(doc, 'database/db_manager.py - 待办事项操作')
    
    add_code_line(doc, 159, '    # ========== 待办事项操作 ==========', '注释：待办事项的CRUD操作')
    add_code_line(doc, 160, '    ', '')
    add_code_line(doc, 161, '    def get_all_todos(self, category_id: int = None, completed: bool = None,', '获取待办列表，支持筛选')
    add_code_line(doc, 162, '                      search_keyword: str = None) -> List[Todo]:', '')
    add_code_line(doc, 163, '        """获取待办事项列表"""', '')
    add_code_line(doc, 164, '        with self.get_connection() as conn:', '')
    add_code_line(doc, 165, '            cursor = conn.cursor()', '')
    add_code_line(doc, 166, '            ', '')
    add_code_line(doc, 167, "            query = '''", '构建动态SQL查询')
    add_code_line(doc, 168, '                SELECT t.*, c.name as category_name, c.color as category_color', '选择todos表所有字段和categories表的名称、颜色')
    add_code_line(doc, 169, '                FROM todos t', '从todos表，别名为t')
    add_code_line(doc, 170, '                LEFT JOIN categories c ON t.category_id = c.id', '左连接categories表，关联条件是category_id')
    add_code_line(doc, 171, "                WHERE 1=1", 'WHERE 1=1 是技巧，方便后面动态添加AND条件')
    add_code_line(doc, 172, "            '''", '')
    add_code_line(doc, 173, '            params = []', '参数列表，用于参数化查询')
    add_code_line(doc, 174, '            ', '')
    add_code_line(doc, 175, '            if category_id is not None:', '如果指定了分类')
    add_code_line(doc, 176, "                query += ' AND t.category_id = ?'", '添加分类筛选条件')
    add_code_line(doc, 177, '                params.append(category_id)', '添加参数')
    add_code_line(doc, 178, '            ', '')
    add_code_line(doc, 179, '            if completed is not None:', '如果指定了完成状态')
    add_code_line(doc, 180, "                query += ' AND t.completed = ?'", '')
    add_code_line(doc, 181, '                params.append(1 if completed else 0)', '布尔转整数（SQLite没有布尔类型）')
    add_code_line(doc, 182, '            ', '')
    add_code_line(doc, 183, '            if search_keyword:', '如果有关键词搜索')
    add_code_line(doc, 184, "                query += ' AND (t.title LIKE ? OR t.description LIKE ?)'", '标题或描述包含关键词')
    add_code_line(doc, 185, '                params.extend([f\'%{search_keyword}%\', f\'%{search_keyword}%\'])', '添加通配符%实现模糊匹配')
    add_code_line(doc, 186, '            ', '')
    add_code_line(doc, 187, "            query += ' ORDER BY t.completed, t.priority, t.created_at DESC'", '排序：先完成状态，再优先级，再创建时间倒序')
    add_code_line(doc, 188, '            ', '')
    add_code_line(doc, 189, '            cursor.execute(query, params)', '执行动态构建的SQL')
    add_code_line(doc, 190, '            return [self._row_to_todo(row) for row in cursor.fetchall()]', '')
    add_code_line(doc, 191, '    ', '')
    add_code_line(doc, 192, '    def get_todo_by_id(self, todo_id: int) -> Optional[Todo]:', '根据ID获取单个待办')
    add_code_line(doc, 193, '        """根据ID获取待办事项"""', '')
    add_code_line(doc, 194, '        with self.get_connection() as conn:', '')
    add_code_line(doc, 195, '            cursor = conn.cursor()', '')
    add_code_line(doc, 196, '            cursor.execute(', '')
    add_code_line(doc, 197, "                '''SELECT t.*, c.name as category_name, c.color as category_color", '')
    add_code_line(doc, 198, '                   FROM todos t', '')
    add_code_line(doc, 199, '                   LEFT JOIN categories c ON t.category_id = c.id', '')
    add_code_line(doc, 200, "                   WHERE t.id = ?''',", '')
    add_code_line(doc, 201, '                (todo_id,)', '')
    add_code_line(doc, 202, '            )', '')
    add_code_line(doc, 203, '            row = cursor.fetchone()', '')
    add_code_line(doc, 204, '            return self._row_to_todo(row) if row else None', '')
    add_code_line(doc, 205, '    ', '')
    add_code_line(doc, 206, '    def add_todo(self, title: str, description: str = \'\', priority: int = 2,', '添加待办事项')
    add_code_line(doc, 207, '                 category_id: int = None, due_date: datetime = None) -> Todo:', '')
    add_code_line(doc, 208, '        """添加新待办事项"""', '')
    add_code_line(doc, 209, '        with self.get_connection() as conn:', '')
    add_code_line(doc, 210, '            cursor = conn.cursor()', '')
    add_code_line(doc, 211, '            ', '')
    add_code_line(doc, 212, '            due_date_str = due_date.isoformat() if due_date else None', 'datetime转ISO格式字符串')
    add_code_line(doc, 213, '            ', '')
    add_code_line(doc, 214, '            cursor.execute(', '')
    add_code_line(doc, 215, "                '''INSERT INTO todos (title, description, priority, category_id, due_date)", '')
    add_code_line(doc, 216, "                   VALUES (?, ?, ?, ?, ?)''',", '')
    add_code_line(doc, 217, '                (title, description, priority, category_id, due_date_str)', '')
    add_code_line(doc, 218, '            )', '')
    add_code_line(doc, 219, '            conn.commit()', '')
    add_code_line(doc, 220, '            todo_id = cursor.lastrowid', '')
    add_code_line(doc, 221, '            return self.get_todo_by_id(todo_id)', '')
    add_code_line(doc, 222, '    ', '')
    add_code_line(doc, 223, '    def update_todo(self, todo_id: int, title: str = None, description: str = None,', '更新待办事项')
    add_code_line(doc, 224, '                    priority: int = None, category_id: int = None,', '')
    add_code_line(doc, 225, '                    due_date: datetime = None, completed: bool = None) -> bool:', '')
    add_code_line(doc, 226, '        """更新待办事项"""', '')
    add_code_line(doc, 227, '        with self.get_connection() as conn:', '')
    add_code_line(doc, 228, '            cursor = conn.cursor()', '')
    add_code_line(doc, 229, '            ', '')
    add_code_line(doc, 230, '            updates = []', '存储要更新的字段')
    add_code_line(doc, 231, '            params = []', '存储参数值')
    add_code_line(doc, 232, '            ', '')
    add_code_line(doc, 233, '            if title is not None:', '如果提供了标题就更新')
    add_code_line(doc, 234, "                updates.append('title = ?')", '添加字段赋值语句')
    add_code_line(doc, 235, '                params.append(title)', '')
    add_code_line(doc, 236, '            if description is not None:', '')
    add_code_line(doc, 237, "                updates.append('description = ?')", '')
    add_code_line(doc, 238, '                params.append(description)', '')
    add_code_line(doc, 239, '            if priority is not None:', '')
    add_code_line(doc, 240, "                updates.append('priority = ?')", '')
    add_code_line(doc, 241, '                params.append(priority)', '')
    add_code_line(doc, 242, '            if category_id is not None:', '')
    add_code_line(doc, 243, "                updates.append('category_id = ?')", '')
    add_code_line(doc, 244, '                params.append(category_id)', '')
    add_code_line(doc, 245, '            if due_date is not None:', '')
    add_code_line(doc, 246, "                updates.append('due_date = ?')", '')
    add_code_line(doc, 247, '                params.append(due_date.isoformat())', '')
    add_code_line(doc, 248, '            if completed is not None:', '')
    add_code_line(doc, 249, "                updates.append('completed = ?')", '')
    add_code_line(doc, 250, '                params.append(1 if completed else 0)', '')
    add_code_line(doc, 251, '            ', '')
    add_code_line(doc, 252, '            if not updates:', '如果没有要更新的字段')
    add_code_line(doc, 253, '                return False', '')
    add_code_line(doc, 254, '            ', '')
    add_code_line(doc, 255, "            updates.append('updated_at = CURRENT_TIMESTAMP')", '自动更新时间戳')
    add_code_line(doc, 256, '            params.append(todo_id)', '最后添加WHERE条件的参数')
    add_code_line(doc, 257, '            ', '')
    add_code_line(doc, 258, "            query = f\"UPDATE todos SET {', '.join(updates)} WHERE id = ?\"", '拼接SQL语句')
    add_code_line(doc, 259, '            cursor.execute(query, params)', '')
    add_code_line(doc, 260, '            conn.commit()', '')
    add_code_line(doc, 261, '            return cursor.rowcount > 0', '')
    add_code_line(doc, 262, '    ', '')
    add_code_line(doc, 263, '    def toggle_todo_completed(self, todo_id: int) -> bool:', '切换完成状态')
    add_code_line(doc, 264, '        """切换待办事项完成状态"""', '')
    add_code_line(doc, 265, '        with self.get_connection() as conn:', '')
    add_code_line(doc, 266, '            cursor = conn.cursor()', '')
    add_code_line(doc, 267, '            cursor.execute(', '')
    add_code_line(doc, 268, "                'UPDATE todos SET completed = NOT completed, updated_at = CURRENT_TIMESTAMP WHERE id = ?',", 'NOT操作符取反布尔值')
    add_code_line(doc, 269, '                (todo_id,)', '')
    add_code_line(doc, 270, '            )', '')
    add_code_line(doc, 271, '            conn.commit()', '')
    add_code_line(doc, 272, '            return cursor.rowcount > 0', '')
    add_code_line(doc, 273, '    ', '')
    add_code_line(doc, 274, '    def delete_todo(self, todo_id: int) -> bool:', '删除待办')
    add_code_line(doc, 275, '        """删除待办事项"""', '')
    add_code_line(doc, 276, '        with self.get_connection() as conn:', '')
    add_code_line(doc, 277, "            cursor.execute('DELETE FROM todos WHERE id = ?', (todo_id,))", '')
    add_code_line(doc, 278, '            conn.commit()', '')
    add_code_line(doc, 279, '            return cursor.rowcount > 0', '')
    add_code_line(doc, 280, '    ', '')
    add_code_line(doc, 281, '    def get_todo_stats(self) -> dict:', '获取统计信息')
    add_code_line(doc, 282, '        """获取待办事项统计信息"""', '')
    add_code_line(doc, 283, '        with self.get_connection() as conn:', '')
    add_code_line(doc, 284, '            cursor = conn.cursor()', '')
    add_code_line(doc, 285, '            ', '')
    add_code_line(doc, 286, '            cursor.execute(\'SELECT COUNT(*) FROM todos\')', '统计总数量')
    add_code_line(doc, 287, '            total = cursor.fetchone()[0]', '')
    add_code_line(doc, 288, '            ', '')
    add_code_line(doc, 289, '            cursor.execute(\'SELECT COUNT(*) FROM todos WHERE completed = 1\')', '统计已完成数量')
    add_code_line(doc, 290, '            completed = cursor.fetchone()[0]', '')
    add_code_line(doc, 291, '            ', '')
    add_code_line(doc, 292, '            return {', '返回统计字典')
    add_code_line(doc, 293, "                'total': total,", '总数')
    add_code_line(doc, 294, "                'completed': completed,", '已完成数')
    add_code_line(doc, 295, "                'pending': total - completed", '待办数=总数-已完成')
    add_code_line(doc, 296, '            }', '')
    add_code_line(doc, 297, '', '')
    add_code_line(doc, 298, '', '')
    
    doc.add_page_break()
    
    # ==================== GUI模块 ====================
    add_file_section(doc, 'database/__init__.py - 数据库包初始化')
    
    add_code_line(doc, 1, '"""数据库模块"""', '模块文档字符串')
    add_code_line(doc, 2, 'from .db_manager import DBManager', '从当前包的db_manager模块导入DBManager类')
    add_code_line(doc, 3, 'from .models import Category, Todo', '从models模块导入Category和Todo类')
    add_code_line(doc, 4, '', '')
    add_code_line(doc, 5, "__all__ = ['DBManager', 'Category', 'Todo']", '定义该包对外暴露的公共接口')
    
    doc.add_page_break()
    
    add_file_section(doc, 'gui/__init__.py - GUI包初始化')
    
    add_code_line(doc, 1, '"""GUI 模块"""', '')
    add_code_line(doc, 2, 'from .main_window import MainWindow', '')
    add_code_line(doc, 3, '', '')
    add_code_line(doc, 4, "__all__ = ['MainWindow']", '')
    
    doc.add_page_break()
    
    add_file_section(doc, 'gui/main_window.py - 主窗口界面')
    
    doc.add_paragraph('【模块说明】应用程序的主界面，使用tkinter构建。采用典型的桌面应用布局：左侧分类导航、右侧任务列表、顶部工具栏。实现了MVC模式中的View（视图）部分。')
    
    add_code_line(doc, 1, '"""主窗口"""', '')
    add_code_line(doc, 2, 'import tkinter as tk', '导入tkinter并别名为tk')
    add_code_line(doc, 3, 'from tkinter import ttk, messagebox', '从tkinter导入ttk（主题组件）和messagebox（消息对话框）')
    add_code_line(doc, 4, 'from config import WINDOW_TITLE, WINDOW_WIDTH, WINDOW_HEIGHT, PRIORITY_NAMES, PRIORITY_COLORS', '导入配置')
    add_code_line(doc, 5, 'from database import DBManager', '导入数据库管理器')
    add_code_line(doc, 6, 'from .todo_form import TodoFormDialog', '从当前包导入待办表单对话框')
    add_code_line(doc, 7, 'from .category_dialog import CategoryDialog', '导入分类管理对话框')
    add_code_line(doc, 8, '', '')
    add_code_line(doc, 9, '', '')
    add_code_line(doc, 10, 'class MainWindow:', '定义主窗口类')
    add_code_line(doc, 11, '    """应用程序主窗口"""', '')
    add_code_line(doc, 12, '    ', '')
    add_code_line(doc, 13, '    def __init__(self):', '构造方法')
    add_code_line(doc, 14, '        self.root = tk.Tk()', '创建Tk根窗口，这是tkinter应用的入口')
    add_code_line(doc, 15, '        self.root.title(WINDOW_TITLE)', '设置窗口标题')
    add_code_line(doc, 16, '        self.root.geometry(f\'{WINDOW_WIDTH}x{WINDOW_HEIGHT}\')', '设置窗口大小')
    add_code_line(doc, 17, '        self.root.minsize(700, 450)', '设置最小窗口尺寸，防止用户缩放过小')
    add_code_line(doc, 18, '        ', '')
    add_code_line(doc, 19, '        # 初始化数据库', '注释')
    add_code_line(doc, 20, '        self.db_manager = DBManager()', '创建数据库管理器实例，会自动初始化表')
    add_code_line(doc, 21, '        ', '')
    add_code_line(doc, 22, '        # 当前筛选状态', '注释')
    add_code_line(doc, 23, '        self.current_category_id = None', '当前选中的分类ID，None表示全部')
    add_code_line(doc, 24, "        self.current_filter = 'all'  # all, completed, pending", '当前筛选条件')
    add_code_line(doc, 25, '        ', '')
    add_code_line(doc, 26, '        self.create_widgets()', '调用方法创建界面组件')
    add_code_line(doc, 27, '        self.refresh_categories()', '加载分类列表')
    add_code_line(doc, 28, '        self.refresh_todos()', '加载待办列表')
    add_code_line(doc, 29, '    ', '')
    add_code_line(doc, 30, '    def create_widgets(self):', '创建界面组件的方法')
    add_code_line(doc, 31, '        """创建界面组件"""', '')
    add_code_line(doc, 32, '        # 顶部工具栏', '注释')
    add_code_line(doc, 33, '        toolbar = ttk.Frame(self.root)', '创建Frame容器作为工具栏')
    add_code_line(doc, 34, "        toolbar.pack(fill='x', padx=5, pady=5)", 'pack布局：水平填充，设置外边距')
    add_code_line(doc, 35, '        ', '')
    add_code_line(doc, 36, "        ttk.Button(toolbar, text='+ 新建待办', command=self.add_todo).pack(side='left', padx=5)", '添加按钮：新建待办，点击调用add_todo方法')
    add_code_line(doc, 37, "        ttk.Separator(toolbar, orient='vertical').pack(side='left', fill='y', padx=5)", '添加垂直分隔线')
    add_code_line(doc, 38, "        ttk.Button(toolbar, text='管理分类', command=self.manage_categories).pack(side='left', padx=5)", '管理分类按钮')
    add_code_line(doc, 39, '        ', '')
    add_code_line(doc, 40, '        # 主内容区（左右分割）', '注释')
    add_code_line(doc, 41, "        paned = ttk.PanedWindow(self.root, orient='horizontal')", '创建可拖动的分割窗口，水平方向')
    add_code_line(doc, 42, "        paned.pack(fill='both', expand=True, padx=5, pady=5)", '填充整个剩余空间')
    add_code_line(doc, 43, '        ', '')
    add_code_line(doc, 44, "        # 左侧分类面板", '注释')
    add_code_line(doc, 45, "        left_frame = ttk.LabelFrame(paned, text='分类', padding=5)", '带标签的框架容器')
    add_code_line(doc, 46, "        paned.add(left_frame, weight=1)", '添加到分割窗，weight设置相对大小')
    add_code_line(doc, 47, '        ', '')
    add_code_line(doc, 48, "        self.category_listbox = tk.Listbox(left_frame, selectmode='single', height=20)", '创建列表框：单选模式')
    add_code_line(doc, 49, "        self.category_listbox.pack(fill='both', expand=True)", '填充框架')
    add_code_line(doc, 50, "        self.category_listbox.bind('<<ListboxSelect>>', self.on_category_select)", '绑定选择事件')
    add_code_line(doc, 51, '        ', '')
    add_code_line(doc, 52, "        ttk.Button(left_frame, text='刷新', command=self.refresh_categories).pack(fill='x', pady=5)", '刷新按钮')
    add_code_line(doc, 53, '        ', '')
    add_code_line(doc, 54, '        # 右侧任务列表面板', '注释')
    add_code_line(doc, 55, '        right_frame = ttk.Frame(paned)', '')
    add_code_line(doc, 56, '        paned.add(right_frame, weight=3)', '右侧占3份宽度')
    add_code_line(doc, 57, '        ', '')
    add_code_line(doc, 58, '        # 筛选栏', '注释')
    add_code_line(doc, 59, '        filter_frame = ttk.Frame(right_frame)', '')
    add_code_line(doc, 60, "        filter_frame.pack(fill='x', pady=5)", '')
    add_code_line(doc, 61, '        ', '')
    add_code_line(doc, 62, "        ttk.Label(filter_frame, text='筛选:').pack(side='left', padx=5)", '筛选标签')
    add_code_line(doc, 63, "        self.filter_var = tk.StringVar(value='all')", '创建字符串变量，默认值为all')
    add_code_line(doc, 64, '        filter_combo = ttk.Combobox(filter_frame, textvariable=self.filter_var,', '下拉选择框')
    add_code_line(doc, 65, "                                    values=['全部', '已完成', '未完成'],", '下拉选项')
    add_code_line(doc, 66, "                                    state='readonly', width=10)", '只读状态，宽度10字符')
    add_code_line(doc, 67, "        filter_combo.pack(side='left', padx=5)", '')
    add_code_line(doc, 68, "        filter_combo.bind('<<ComboboxSelect>>', self.on_filter_change)", '绑定选择变化事件')
    
    doc.add_page_break()
    
    add_file_section(doc, 'gui/main_window.py - 搜索和任务列表')
    
    add_code_line(doc, 70, "        ttk.Label(filter_frame, text='搜索:').pack(side='left', padx=5)", '搜索标签')
    add_code_line(doc, 71, '        self.search_var = tk.StringVar()', '搜索框绑定的变量')
    add_code_line(doc, 72, "        search_entry = ttk.Entry(filter_frame, textvariable=self.search_var, width=25)", '输入框')
    add_code_line(doc, 73, "        search_entry.pack(side='left', padx=5)", '')
    add_code_line(doc, 74, "        ttk.Button(filter_frame, text='搜索', command=self.refresh_todos).pack(side='left', padx=5)", '搜索按钮')
    add_code_line(doc, 75, "        ttk.Button(filter_frame, text='清除', command=self.clear_search).pack(side='left', padx=5)", '清除按钮')
    add_code_line(doc, 76, '        ', '')
    add_code_line(doc, 77, '        # 任务列表', '注释')
    add_code_line(doc, 78, '        list_frame = ttk.Frame(right_frame)', '')
    add_code_line(doc, 79, "        list_frame.pack(fill='both', expand=True, pady=5)", '')
    add_code_line(doc, 80, '        ', '')
    add_code_line(doc, 81, "        columns = ('title', 'category', 'priority', 'due_date', 'completed')", '定义表格列')
    add_code_line(doc, 82, '        self.todo_tree = ttk.Treeview(list_frame, columns=columns, show=\'headings\',', '创建树形表格视图')
    add_code_line(doc, 83, "                                     height=15, selectmode='browse')", '高度15行，browse模式（单选）')
    add_code_line(doc, 84, '        ', '')
    add_code_line(doc, 85, "        self.todo_tree.heading('title', text='标题')", '设置列标题')
    add_code_line(doc, 86, "        self.todo_tree.heading('category', text='分类')", '')
    add_code_line(doc, 87, "        self.todo_tree.heading('priority', text='优先级')", '')
    add_code_line(doc, 88, "        self.todo_tree.heading('due_date', text='截止日期')", '')
    add_code_line(doc, 89, "        self.todo_tree.heading('completed', text='状态')", '')
    add_code_line(doc, 90, '        ', '')
    add_code_line(doc, 91, "        self.todo_tree.column('title', width=200)", '设置列宽度')
    add_code_line(doc, 92, "        self.todo_tree.column('category', width=80)", '')
    add_code_line(doc, 93, "        self.todo_tree.column('priority', width=60)", '')
    add_code_line(doc, 94, "        self.todo_tree.column('due_date', width=100)", '')
    add_code_line(doc, 95, "        self.todo_tree.column('completed', width=60)", '')
    add_code_line(doc, 96, '        ', '')
    add_code_line(doc, 97, '        # 滚动条', '注释')
    add_code_line(doc, 98, "        scrollbar_y = ttk.Scrollbar(list_frame, orient='vertical', command=self.todo_tree.yview)", '垂直滚动条')
    add_code_line(doc, 99, "        scrollbar_x = ttk.Scrollbar(list_frame, orient='horizontal', command=self.todo_tree.xview)", '水平滚动条')
    add_code_line(doc, 100, '        self.todo_tree.configure(yscrollcommand=scrollbar_y.set, xscrollcommand=scrollbar_x.set)', '配置滚动条关联')
    add_code_line(doc, 101, '        ', '')
    add_code_line(doc, 102, "        self.todo_tree.grid(row=0, column=0, sticky='nsew')", '使用grid布局')
    add_code_line(doc, 103, "        scrollbar_y.grid(row=0, column=1, sticky='ns')", '')
    add_code_line(doc, 104, "        scrollbar_x.grid(row=1, column=0, sticky='ew')", '')
    add_code_line(doc, 105, '        ', '')
    add_code_line(doc, 106, '        list_frame.columnconfigure(0, weight=1)', '设置列权重')
    add_code_line(doc, 107, '        list_frame.rowconfigure(0, weight=1)', '')
    add_code_line(doc, 108, '        ', '')
    add_code_line(doc, 109, '        # 绑定事件', '注释')
    add_code_line(doc, 110, "        self.todo_tree.bind('<Double-1>', self.edit_todo)", '双击编辑')
    add_code_line(doc, 111, "        self.todo_tree.bind('<Button-3>', self.show_context_menu)", '右键菜单（Button-3是右键）')
    add_code_line(doc, 112, '        ', '')
    add_code_line(doc, 113, '        # 按钮区域', '注释')
    add_code_line(doc, 114, '        btn_frame = ttk.Frame(right_frame)', '')
    add_code_line(doc, 115, "        btn_frame.pack(fill='x', pady=5)", '')
    add_code_line(doc, 116, "        ttk.Button(btn_frame, text='标记完成/未完成', command=self.toggle_completed).pack(side='left', padx=5)", '')
    add_code_line(doc, 117, "        ttk.Button(btn_frame, text='编辑', command=self.edit_todo).pack(side='left', padx=5)", '')
    add_code_line(doc, 118, "        ttk.Button(btn_frame, text='删除', command=self.delete_todo).pack(side='left', padx=5)", '')
    add_code_line(doc, 119, "        ttk.Button(btn_frame, text='刷新列表', command=self.refresh_todos).pack(side='right', padx=5)", '')
    add_code_line(doc, 120, '        ', '')
    add_code_line(doc, 121, '        # 状态栏', '注释')
    add_code_line(doc, 122, "        self.status_var = tk.StringVar(value='就绪')", '状态栏文字变量')
    add_code_line(doc, 123, "        status_bar = ttk.Label(self.root, textvariable=self.status_var, relief='sunken', anchor='w')", '凹陷效果，左对齐')
    add_code_line(doc, 124, "        status_bar.pack(fill='x', side='bottom')", '底部填充')
    
    doc.add_page_break()
    
    add_file_section(doc, 'gui/main_window.py - 刷新和事件处理')
    
    add_code_line(doc, 127, '    def refresh_categories(self):', '刷新分类列表')
    add_code_line(doc, 128, '        """刷新分类列表"""', '')
    add_code_line(doc, 129, '        self.category_listbox.delete(0, tk.END)', '清空列表框')
    add_code_line(doc, 130, "        self.category_listbox.insert(tk.END, '全部')", '插入"全部"选项')
    add_code_line(doc, 131, '        ', '')
    add_code_line(doc, 132, '        categories = self.db_manager.get_all_categories()', '从数据库获取分类')
    add_code_line(doc, 133, "        self.category_map = {'全部': None}", '创建名称到ID的映射')
    add_code_line(doc, 134, '        ', '')
    add_code_line(doc, 135, '        for cat in categories:', '遍历分类')
    add_code_line(doc, 136, '            self.category_listbox.insert(tk.END, cat.name)', '添加到列表框')
    add_code_line(doc, 137, '            self.category_map[cat.name] = cat.id', '保存映射关系')
    add_code_line(doc, 138, '    ', '')
    add_code_line(doc, 139, '    def on_category_select(self, event):', '分类选择事件处理')
    add_code_line(doc, 140, '        """分类选择事件"""', '')
    add_code_line(doc, 141, '        selection = self.category_listbox.curselection()', '获取选中项索引')
    add_code_line(doc, 142, '        if selection:', '如果有选中')
    add_code_line(doc, 143, '            category_name = self.category_listbox.get(selection[0])', '获取选中的分类名称')
    add_code_line(doc, 144, '            self.current_category_id = self.category_map.get(category_name)', '获取对应ID')
    add_code_line(doc, 145, '            self.refresh_todos()', '刷新待办列表')
    add_code_line(doc, 146, '    ', '')
    add_code_line(doc, 147, '    def on_filter_change(self, event):', '筛选变化事件')
    add_code_line(doc, 148, '        """筛选条件改变"""', '')
    add_code_line(doc, 149, '        filter_text = self.filter_var.get()', '获取当前筛选文字')
    add_code_line(doc, 150, "        if filter_text == '全部':", '')
    add_code_line(doc, 151, "            self.current_filter = 'all'", '')
    add_code_line(doc, 152, "        elif filter_text == '已完成':", '')
    add_code_line(doc, 153, "            self.current_filter = 'completed'", '')
    add_code_line(doc, 154, '        else:', '')
    add_code_line(doc, 155, "            self.current_filter = 'pending'", '')
    add_code_line(doc, 156, '        self.refresh_todos()', '')
    add_code_line(doc, 157, '    ', '')
    add_code_line(doc, 158, '    def clear_search(self):', '清除搜索')
    add_code_line(doc, 159, '        """清除搜索"""', '')
    add_code_line(doc, 160, "        self.search_var.set('')", '清空搜索变量')
    add_code_line(doc, 161, '        self.refresh_todos()', '刷新列表')
    add_code_line(doc, 162, '    ', '')
    add_code_line(doc, 163, '    def refresh_todos(self):', '刷新待办列表（核心方法）')
    add_code_line(doc, 164, '        """刷新待办列表"""', '')
    add_code_line(doc, 165, '        # 清空列表', '注释')
    add_code_line(doc, 166, '        for item in self.todo_tree.get_children():', '获取所有行')
    add_code_line(doc, 167, '            self.todo_tree.delete(item)', '逐行删除')
    add_code_line(doc, 168, '        ', '')
    add_code_line(doc, 169, '        # 获取筛选条件', '注释')
    add_code_line(doc, 170, '        completed = None', '')
    add_code_line(doc, 171, "        if self.current_filter == 'completed':", '')
    add_code_line(doc, 172, '            completed = True', '')
    add_code_line(doc, 173, "        elif self.current_filter == 'pending':", '')
    add_code_line(doc, 174, '            completed = False', '')
    add_code_line(doc, 175, '        ', '')
    add_code_line(doc, 176, '        search_keyword = self.search_var.get().strip() or None', '获取搜索关键词，去除空格')
    add_code_line(doc, 177, '        ', '')
    add_code_line(doc, 178, '        # 加载待办事项', '注释')
    add_code_line(doc, 179, '        todos = self.db_manager.get_all_todos(', '调用数据库方法获取数据')
    add_code_line(doc, 180, '            category_id=self.current_category_id,', '传入分类筛选')
    add_code_line(doc, 181, '            completed=completed,', '传入完成状态筛选')
    add_code_line(doc, 182, '            search_keyword=search_keyword', '传入搜索关键词')
    add_code_line(doc, 183, '        )', '')
    add_code_line(doc, 184, '        ', '')
    add_code_line(doc, 185, '        self.todo_items = {}  # item -> id 映射', '创建字典保存行到ID的映射')
    add_code_line(doc, 186, '        ', '')
    add_code_line(doc, 187, '        for todo in todos:', '遍历待办事项')
    add_code_line(doc, 188, "            status = '已完成' if todo.completed else '未完成'", '状态文字')
    add_code_line(doc, 189, '            priority_text = PRIORITY_NAMES.get(todo.priority, \'中\')', '获取优先级中文')
    add_code_line(doc, 190, '            due_date = todo.due_date.strftime(\'%Y-%m-%d\') if todo.due_date else \'\'', '格式化日期')
    add_code_line(doc, 191, '            category_name = todo.category.name if todo.category else \'未分类\'', '获取分类名')
    add_code_line(doc, 192, '            ', '')
    add_code_line(doc, 193, '            values = (', '组装表格数据')
    add_code_line(doc, 194, '                todo.title,', '')
    add_code_line(doc, 195, '                category_name,', '')
    add_code_line(doc, 196, '                priority_text,', '')
    add_code_line(doc, 197, '                due_date,', '')
    add_code_line(doc, 198, '                status', '')
    add_code_line(doc, 199, '            )', '')
    add_code_line(doc, 200, '            ', '')
    add_code_line(doc, 201, "            item = self.todo_tree.insert('', 'end', values=values)", '插入新行到表格末尾')
    add_code_line(doc, 202, '            self.todo_items[item] = todo.id', '保存映射关系')
    add_code_line(doc, 203, '            ', '')
    add_code_line(doc, 204, '            # 根据优先级设置颜色标签', '注释')
    add_code_line(doc, 205, '            tag = f\'priority_{todo.priority}\'', '创建标签名')
    add_code_line(doc, 206, '            if not self.todo_tree.tag_has(tag):', '如果标签不存在')
    add_code_line(doc, 207, '                color = PRIORITY_COLORS.get(todo.priority, \'#000000\')', '获取颜色')
    add_code_line(doc, 208, '                self.todo_tree.tag_configure(tag, foreground=color)', '配置标签颜色')
    add_code_line(doc, 209, '            self.todo_tree.item(item, tags=(tag,))', '给行添加标签')
    add_code_line(doc, 210, '            ', '')
    add_code_line(doc, 211, '            # 已完成项目灰色显示', '注释')
    add_code_line(doc, 212, '            if todo.completed:', '如果已完成')
    add_code_line(doc, 213, "                self.todo_tree.item(item, tags=(tag, 'completed'))", '添加completed标签')
    add_code_line(doc, 214, '                if not self.todo_tree.tag_has(\'completed\'):', '如果completed标签不存在')
    add_code_line(doc, 215, "                    self.todo_tree.tag_configure('completed', foreground='gray')", '设为灰色')
    add_code_line(doc, 216, '        ', '')
    add_code_line(doc, 217, '        # 更新状态栏', '注释')
    add_code_line(doc, 218, '        stats = self.db_manager.get_todo_stats()', '获取统计')
    add_code_line(doc, 219, '        self.status_var.set(', '设置状态栏文字')
    
    doc.add_page_break()
    
    add_file_section(doc, 'gui/main_window.py - 操作功能方法')
    
    add_code_line(doc, 221, '    def add_todo(self):', '添加待办')
    add_code_line(doc, 222, '        """添加待办事项"""', '')
    add_code_line(doc, 223, '        dialog = TodoFormDialog(self.root, self.db_manager,', '创建对话框')
    add_code_line(doc, 224, '                               category_id=self.current_category_id)', '传入当前分类作为默认值')
    add_code_line(doc, 225, '        result = dialog.show()', '显示对话框并等待结果')
    add_code_line(doc, 226, '        ', '')
    add_code_line(doc, 227, '        if result:', '如果用户点击了保存')
    add_code_line(doc, 228, '            self.db_manager.add_todo(**result)', '解包字典为关键字参数添加')
    add_code_line(doc, 229, '            self.refresh_todos()', '刷新列表')
    add_code_line(doc, 230, '    ', '')
    add_code_line(doc, 231, '    def edit_todo(self, event=None):', '编辑待办')
    add_code_line(doc, 232, '        """编辑待办事项"""', '')
    add_code_line(doc, 233, '        selection = self.todo_tree.selection()', '获取选中项')
    add_code_line(doc, 234, '        if not selection:', '如果没有选中')
    add_code_line(doc, 235, "            messagebox.showwarning('提示', '请先选择一个待办事项')", '显示警告')
    add_code_line(doc, 236, '            return', '')
    add_code_line(doc, 237, '        ', '')
    add_code_line(doc, 238, '        item = selection[0]', '获取第一个选中项')
    add_code_line(doc, 239, '        todo_id = self.todo_items.get(item)', '通过映射获取ID')
    add_code_line(doc, 240, '        todo = self.db_manager.get_todo_by_id(todo_id)', '查询待办详情')
    add_code_line(doc, 241, '        ', '')
    add_code_line(doc, 242, '        if todo:', '如果找到数据')
    add_code_line(doc, 243, '            dialog = TodoFormDialog(self.root, self.db_manager, todo=todo)', '传入选中待办进行编辑')
    add_code_line(doc, 244, '            result = dialog.show()', '')
    add_code_line(doc, 245, '            ', '')
    add_code_line(doc, 246, '            if result:', '')
    add_code_line(doc, 247, '                self.db_manager.update_todo(todo_id, **result)', '更新数据')
    add_code_line(doc, 248, '                self.refresh_todos()', '')
    add_code_line(doc, 249, '    ', '')
    add_code_line(doc, 250, '    def delete_todo(self):', '删除待办')
    add_code_line(doc, 251, '        """删除待办事项"""', '')
    add_code_line(doc, 252, '        selection = self.todo_tree.selection()', '')
    add_code_line(doc, 253, '        if not selection:', '')
    add_code_line(doc, 254, "            messagebox.showwarning('提示', '请先选择一个待办事项')", '')
    add_code_line(doc, 255, '            return', '')
    add_code_line(doc, 256, '        ', '')
    add_code_line(doc, 257, '        item = selection[0]', '')
    add_code_line(doc, 258, '        todo_id = self.todo_items.get(item)', '')
    add_code_line(doc, 259, '        todo_title = self.todo_tree.item(item, \'values\')[0]', '获取标题')
    add_code_line(doc, 260, '        ', '')
    add_code_line(doc, 261, '        if messagebox.askyesno(\'确认\', f\'确定要删除 "{todo_title}" 吗？\'):', '确认对话框')
    add_code_line(doc, 262, '            self.db_manager.delete_todo(todo_id)', '删除')
    add_code_line(doc, 263, '            self.refresh_todos()', '')
    add_code_line(doc, 264, '    ', '')
    add_code_line(doc, 265, '    def toggle_completed(self):', '切换完成状态')
    add_code_line(doc, 266, '        """切换完成状态"""', '')
    add_code_line(doc, 267, '        selection = self.todo_tree.selection()', '')
    add_code_line(doc, 268, '        if not selection:', '')
    add_code_line(doc, 269, "            messagebox.showwarning('提示', '请先选择一个待办事项')", '')
    add_code_line(doc, 270, '            return', '')
    add_code_line(doc, 271, '        ', '')
    add_code_line(doc, 272, '        item = selection[0]', '')
    add_code_line(doc, 273, '        todo_id = self.todo_items.get(item)', '')
    add_code_line(doc, 274, '        ', '')
    add_code_line(doc, 275, '        self.db_manager.toggle_todo_completed(todo_id)', '切换状态')
    add_code_line(doc, 276, '        self.refresh_todos()', '')
    add_code_line(doc, 277, '    ', '')
    add_code_line(doc, 278, '    def manage_categories(self):', '管理分类')
    add_code_line(doc, 279, '        """管理分类"""', '')
    add_code_line(doc, 280, '        dialog = CategoryDialog(self.root, self.db_manager)', '创建分类对话框')
    add_code_line(doc, 281, '        dialog.show()', '')
    add_code_line(doc, 282, '        self.refresh_categories()', '刷新分类列表')
    add_code_line(doc, 283, '    ', '')
    add_code_line(doc, 284, '    def show_context_menu(self, event):', '显示右键菜单')
    add_code_line(doc, 285, '        """显示右键菜单"""', '')
    add_code_line(doc, 286, '        item = self.todo_tree.identify_row(event.y)', '根据Y坐标确定点击的行')
    add_code_line(doc, 287, '        if item:', '如果点在行上')
    add_code_line(doc, 288, '            self.todo_tree.selection_set(item)', '选中该行')
    add_code_line(doc, 289, '            menu = tk.Menu(self.root, tearoff=0)', '创建菜单，tearoff=0禁止拖拽')
    add_code_line(doc, 290, "            menu.add_command(label='编辑', command=self.edit_todo)", '添加菜单项')
    add_code_line(doc, 291, "            menu.add_command(label='标记完成/未完成', command=self.toggle_completed)", '')
    add_code_line(doc, 292, '            menu.add_separator()', '添加分隔线')
    add_code_line(doc, 293, "            menu.add_command(label='删除', command=self.delete_todo)", '')
    add_code_line(doc, 294, '            menu.post(event.x_root, event.y_root)', '在鼠标位置显示菜单')
    add_code_line(doc, 295, '    ', '')
    add_code_line(doc, 296, '    def run(self):', '运行应用')
    add_code_line(doc, 297, '        """运行应用程序"""', '')
    add_code_line(doc, 298, '        self.root.mainloop()', '启动tkinter事件循环，阻塞直到窗口关闭')
    add_code_line(doc, 299, '', '')
    
    doc.add_page_break()
    
    add_file_section(doc, 'gui/todo_form.py - 待办表单对话框')
    
    doc.add_paragraph('【模块说明】添加/编辑待办事项的对话框。继承自Toplevel，作为模态对话框使用。收集用户输入并返回结果给主窗口。')
    
    add_code_line(doc, 1, '"""待办事项表单对话框"""', '')
    add_code_line(doc, 2, 'import tkinter as tk', '')
    add_code_line(doc, 3, 'from tkinter import ttk, messagebox', '')
    add_code_line(doc, 4, 'from datetime import datetime', '')
    add_code_line(doc, 5, 'from config import PRIORITY_NAMES, PRIORITY_HIGH, PRIORITY_MEDIUM, PRIORITY_LOW', '')
    add_code_line(doc, 6, '', '')
    add_code_line(doc, 7, '', '')
    add_code_line(doc, 8, 'class TodoFormDialog:', '定义表单对话框类')
    add_code_line(doc, 9, '    """待办事项添加/编辑对话框"""', '')
    add_code_line(doc, 10, '    ', '')
    add_code_line(doc, 11, '    def __init__(self, parent, db_manager, todo=None, category_id=None):', '构造方法')
    add_code_line(doc, 12, '        """', '文档字符串开始')
    add_code_line(doc, 13, '        初始化对话框', '')
    add_code_line(doc, 14, '        :param parent: 父窗口', '参数说明：父窗口')
    add_code_line(doc, 15, '        :param db_manager: 数据库管理器', '')
    add_code_line(doc, 16, '        :param todo: 待编辑的待办事项（None表示新建）', '')
    add_code_line(doc, 17, '        :param category_id: 默认选中的分类ID', '')
    add_code_line(doc, 18, '        """', '')
    add_code_line(doc, 19, '        self.parent = parent', '保存父窗口引用')
    add_code_line(doc, 20, '        self.db_manager = db_manager', '保存数据库管理器')
    add_code_line(doc, 21, '        self.todo = todo', '保存待办数据')
    add_code_line(doc, 22, '        self.result = None', '初始化结果为None')
    add_code_line(doc, 23, '        ', '')
    add_code_line(doc, 24, '        self.dialog = tk.Toplevel(parent)', '创建顶级窗口作为对话框')
    add_code_line(doc, 25, "        self.dialog.title('编辑待办' if todo else '添加待办')", '根据模式设置标题')
    add_code_line(doc, 26, "        self.dialog.geometry('450x400')", '设置大小')
    add_code_line(doc, 27, '        self.dialog.transient(parent)', '设为父窗口的临时窗口（不显示在任务栏）')
    add_code_line(doc, 28, '        self.dialog.grab_set()', '模态对话框：阻止与父窗口交互')
    add_code_line(doc, 29, '        ', '')
    add_code_line(doc, 30, '        self.create_widgets()', '')
    add_code_line(doc, 31, '        self.load_data(category_id)', '')
    add_code_line(doc, 32, '        ', '')
    add_code_line(doc, 33, '        # 居中显示', '注释')
    add_code_line(doc, 34, '        self.dialog.update_idletasks()', '更新布局计算')
    add_code_line(doc, 35, '        x = (self.dialog.winfo_screenwidth() - self.dialog.winfo_width()) // 2', '计算居中X坐标')
    add_code_line(doc, 36, '        y = (self.dialog.winfo_screenheight() - self.dialog.winfo_height()) // 2', '计算居中Y坐标')
    add_code_line(doc, 37, '        self.dialog.geometry(f\'+{x}+{y}\')', '应用位置')
    
    doc.add_page_break()
    
    add_file_section(doc, 'gui/todo_form.py - 表单组件')
    
    add_code_line(doc, 39, '    def create_widgets(self):', '创建表单组件')
    add_code_line(doc, 40, '        """创建界面组件"""', '')
    add_code_line(doc, 41, "        padding = {'padx': 10, 'pady': 5}", '定义统一的外边距')
    add_code_line(doc, 42, '        ', '')
    add_code_line(doc, 43, '        # 标题', '注释')
    add_code_line(doc, 44, "        ttk.Label(self.dialog, text='标题:').grid(row=0, column=0, sticky='w', **padding)", '标签：第0行第0列，左对齐')
    add_code_line(doc, 45, '        self.title_var = tk.StringVar()', '标题输入框变量')
    add_code_line(doc, 46, '        self.title_entry = ttk.Entry(self.dialog, textvariable=self.title_var, width=40)', '输入框，宽度40字符')
    add_code_line(doc, 47, "        self.title_entry.grid(row=0, column=1, sticky='ew', **padding)", '第0行第1列，水平填充')
    add_code_line(doc, 48, '        ', '')
    add_code_line(doc, 49, '        # 分类', '注释')
    add_code_line(doc, 50, "        ttk.Label(self.dialog, text='分类:').grid(row=1, column=0, sticky='w', **padding)", '')
    add_code_line(doc, 51, '        self.category_var = tk.StringVar()', '')
    add_code_line(doc, 52, "        self.category_combo = ttk.Combobox(self.dialog, textvariable=self.category_var,", '下拉框')
    add_code_line(doc, 53, "                                           state='readonly', width=37)", '只读模式')
    add_code_line(doc, 54, "        self.category_combo.grid(row=1, column=1, sticky='ew', **padding)", '')
    add_code_line(doc, 55, '        ', '')
    add_code_line(doc, 56, '        # 优先级', '注释')
    add_code_line(doc, 57, "        ttk.Label(self.dialog, text='优先级:').grid(row=2, column=0, sticky='w', **padding)", '')
    add_code_line(doc, 58, '        self.priority_var = tk.IntVar(value=PRIORITY_MEDIUM)', '整型变量，默认中优先级')
    add_code_line(doc, 59, '        priority_frame = ttk.Frame(self.dialog)', '创建框架容纳单选按钮')
    add_code_line(doc, 60, "        priority_frame.grid(row=2, column=1, sticky='w', **padding)", '')
    add_code_line(doc, 61, '        ', '')
    add_code_line(doc, 62, "        ttk.Radiobutton(priority_frame, text='高', variable=self.priority_var,", '单选按钮：高')
    add_code_line(doc, 63, '                       value=PRIORITY_HIGH).pack(side=\'left\', padx=5)', '')
    add_code_line(doc, 64, "        ttk.Radiobutton(priority_frame, text='中', variable=self.priority_var,", '单选按钮：中')
    add_code_line(doc, 65, '                       value=PRIORITY_MEDIUM).pack(side=\'left\', padx=5)', '')
    add_code_line(doc, 66, "        ttk.Radiobutton(priority_frame, text='低', variable=self.priority_var,", '单选按钮：低')
    add_code_line(doc, 67, '                       value=PRIORITY_LOW).pack(side=\'left\', padx=5)', '')
    add_code_line(doc, 68, '        ', '')
    add_code_line(doc, 69, '        # 截止日期', '注释')
    add_code_line(doc, 70, "        ttk.Label(self.dialog, text='截止日期:').grid(row=3, column=0, sticky='w', **padding)", '')
    add_code_line(doc, 71, '        self.due_date_var = tk.StringVar()', '')
    add_code_line(doc, 72, "        self.due_date_entry = ttk.Entry(self.dialog, textvariable=self.due_date_var, width=30)", '')
    add_code_line(doc, 73, "        self.due_date_entry.grid(row=3, column=1, sticky='w', **padding)", '')
    add_code_line(doc, 74, "        ttk.Label(self.dialog, text='(YYYY-MM-DD)').grid(row=3, column=1, sticky='e', padx=10)", '格式提示')
    add_code_line(doc, 75, '        ', '')
    add_code_line(doc, 76, '        # 描述', '注释')
    add_code_line(doc, 77, "        ttk.Label(self.dialog, text='描述:').grid(row=4, column=0, sticky='nw', **padding)", 'nw=西北=左上对齐')
    add_code_line(doc, 78, "        self.desc_text = tk.Text(self.dialog, width=35, height=8, wrap='word')", '多行文本框，自动换行')
    add_code_line(doc, 79, "        self.desc_text.grid(row=4, column=1, sticky='nsew', **padding)", 'nsew=四向填充')
    add_code_line(doc, 80, '        ', '')
    add_code_line(doc, 81, '        # 滚动条', '注释')
    add_code_line(doc, 82, "        scrollbar = ttk.Scrollbar(self.dialog, orient='vertical', command=self.desc_text.yview)", '')
    add_code_line(doc, 83, "        scrollbar.grid(row=4, column=2, sticky='ns')", '')
    add_code_line(doc, 84, "        self.desc_text['yscrollcommand'] = scrollbar.set", '关联滚动条')
    add_code_line(doc, 85, '        ', '')
    add_code_line(doc, 86, '        # 按钮区域', '注释')
    add_code_line(doc, 87, '        btn_frame = ttk.Frame(self.dialog)', '')
    add_code_line(doc, 88, '        btn_frame.grid(row=5, column=0, columnspan=3, pady=15)', '跨3列')
    add_code_line(doc, 89, '        ', '')
    add_code_line(doc, 90, "        ttk.Button(btn_frame, text='保存', command=self.save).pack(side='left', padx=5)", '')
    add_code_line(doc, 91, "        ttk.Button(btn_frame, text='取消', command=self.cancel).pack(side='left', padx=5)", '')
    add_code_line(doc, 92, '        ', '')
    add_code_line(doc, 93, '        # 配置网格权重', '注释')
    add_code_line(doc, 94, '        self.dialog.columnconfigure(1, weight=1)', '第1列可扩展')
    add_code_line(doc, 95, '        self.dialog.rowconfigure(4, weight=1)', '第4行（描述区域）可扩展')
    
    doc.add_page_break()
    
    add_file_section(doc, 'gui/todo_form.py - 数据加载和保存')
    
    add_code_line(doc, 97, '    def load_data(self, default_category_id=None):', '加载数据到表单')
    add_code_line(doc, 98, '        """加载数据"""', '')
    add_code_line(doc, 99, '        # 加载分类列表', '注释')
    add_code_line(doc, 100, '        categories = self.db_manager.get_all_categories()', '')
    add_code_line(doc, 101, '        self.category_map = {cat.name: cat.id for cat in categories}', '字典推导式')
    add_code_line(doc, 102, '        self.category_combo[\'values\'] = list(self.category_map.keys())', '设置下拉选项')
    add_code_line(doc, 103, '        ', '')
    add_code_line(doc, 104, '        if self.todo:', '如果是编辑模式')
    add_code_line(doc, 105, '            # 编辑模式 - 填充现有数据', '注释')
    add_code_line(doc, 106, '            self.title_var.set(self.todo.title)', '填充标题')
    add_code_line(doc, 107, '            self.priority_var.set(self.todo.priority)', '填充优先级')
    add_code_line(doc, 108, "            self.desc_text.insert('1.0', self.todo.description or '')", '填充描述，1.0表示第一行第0列')
    add_code_line(doc, 109, '            ', '')
    add_code_line(doc, 110, '            if self.todo.due_date:', '如果有截止日期')
    add_code_line(doc, 111, "                self.due_date_var.set(self.todo.due_date.strftime('%Y-%m-%d'))", '格式化日期')
    add_code_line(doc, 112, '            ', '')
    add_code_line(doc, 113, '            if self.todo.category_id:', '如果有分类')
    add_code_line(doc, 114, '                for name, cid in self.category_map.items():', '遍历映射')
    add_code_line(doc, 115, '                    if cid == self.todo.category_id:', '找到匹配的分类')
    add_code_line(doc, 116, '                        self.category_var.set(name)', '设置选中')
    add_code_line(doc, 117, '                        break', '跳出循环')
    add_code_line(doc, 118, '        else:', '新建模式')
    add_code_line(doc, 119, '            # 新建模式', '注释')
    add_code_line(doc, 120, '            if default_category_id:', '如果有默认分类')
    add_code_line(doc, 121, '                for name, cid in self.category_map.items():', '')
    add_code_line(doc, 122, '                    if cid == default_category_id:', '')
    add_code_line(doc, 123, '                        self.category_var.set(name)', '')
    add_code_line(doc, 124, '                        break', '')
    add_code_line(doc, 125, '    ', '')
    add_code_line(doc, 126, '    def save(self):', '保存数据')
    add_code_line(doc, 127, '        """保存数据"""', '')
    add_code_line(doc, 128, '        title = self.title_var.get().strip()', '获取并去除首尾空格')
    add_code_line(doc, 129, '        if not title:', '如果标题为空')
    add_code_line(doc, 130, "            messagebox.showerror('错误', '请输入标题', parent=self.dialog)", '显示错误，parent指定对话框父窗口')
    add_code_line(doc, 131, '            return', '')
    add_code_line(doc, 132, '        ', '')
    add_code_line(doc, 133, "        description = self.desc_text.get('1.0', 'end-1c').strip()", '获取所有文本，end-1c去掉末尾换行')
    add_code_line(doc, 134, '        priority = self.priority_var.get()', '')
    add_code_line(doc, 135, '        ', '')
    add_code_line(doc, 136, '        # 获取分类ID', '注释')
    add_code_line(doc, 137, '        category_name = self.category_var.get()', '')
    add_code_line(doc, 138, '        category_id = self.category_map.get(category_name)', '')
    add_code_line(doc, 139, '        ', '')
    add_code_line(doc, 140, '        # 解析日期', '注释')
    add_code_line(doc, 141, '        due_date = None', '')
    add_code_line(doc, 142, '        date_str = self.due_date_var.get().strip()', '')
    add_code_line(doc, 143, '        if date_str:', '如果输入了日期')
    add_code_line(doc, 144, "            try:", '异常处理')
    add_code_line(doc, 145, "                due_date = datetime.strptime(date_str, '%Y-%m-%d')", '按格式解析字符串为datetime')
    add_code_line(doc, 146, '            except ValueError:', '格式错误')
    add_code_line(doc, 147, "                messagebox.showerror('错误', '日期格式不正确，请使用 YYYY-MM-DD 格式',", '')
    add_code_line(doc, 148, '                                   parent=self.dialog)', '')
    add_code_line(doc, 149, '                return', '')
    add_code_line(doc, 150, '        ', '')
    add_code_line(doc, 151, '        self.result = {', '组装结果字典')
    add_code_line(doc, 152, "            'title': title,", '')
    add_code_line(doc, 153, "            'description': description,", '')
    add_code_line(doc, 154, "            'priority': priority,", '')
    add_code_line(doc, 155, "            'category_id': category_id,", '')
    add_code_line(doc, 156, "            'due_date': due_date", '')
    add_code_line(doc, 157, '        }', '')
    add_code_line(doc, 158, '        ', '')
    add_code_line(doc, 159, '        self.dialog.destroy()', '关闭对话框')
    add_code_line(doc, 160, '    ', '')
    add_code_line(doc, 161, '    def cancel(self):', '取消')
    add_code_line(doc, 162, '        """取消"""', '')
    add_code_line(doc, 163, '        self.dialog.destroy()', '关闭对话框（不保存result）')
    add_code_line(doc, 164, '    ', '')
    add_code_line(doc, 165, '    def show(self):', '显示对话框')
    add_code_line(doc, 166, '        """显示对话框并等待结果"""', '')
    add_code_line(doc, 167, '        self.parent.wait_window(self.dialog)', '阻塞等待对话框关闭')
    add_code_line(doc, 168, '        return self.result', '返回结果')
    add_code_line(doc, 169, '', '')
    
    doc.add_page_break()
    
    add_file_section(doc, 'gui/category_dialog.py - 分类管理对话框')
    
    doc.add_paragraph('【模块说明】管理分类的对话框，可以添加新分类、删除分类、修改分类颜色。使用颜色选择器让用户自定义分类颜色。')
    
    add_code_line(doc, 1, '"""分类管理对话框"""', '')
    add_code_line(doc, 2, 'import tkinter as tk', '')
    add_code_line(doc, 3, 'from tkinter import ttk, messagebox, colorchooser', '导入colorchooser颜色选择器')
    add_code_line(doc, 4, '', '')
    add_code_line(doc, 5, '', '')
    add_code_line(doc, 6, 'class CategoryDialog:', '定义分类对话框类')
    add_code_line(doc, 7, '    """分类管理对话框"""', '')
    add_code_line(doc, 8, '    ', '')
    add_code_line(doc, 9, '    def __init__(self, parent, db_manager):', '构造方法')
    add_code_line(doc, 10, '        self.parent = parent', '')
    add_code_line(doc, 11, '        self.db_manager = db_manager', '')
    add_code_line(doc, 12, '        ', '')
    add_code_line(doc, 13, '        self.dialog = tk.Toplevel(parent)', '')
    add_code_line(doc, 14, "        self.dialog.title('管理分类')", '')
    add_code_line(doc, 15, "        self.dialog.geometry('400x350')", '')
    add_code_line(doc, 16, '        self.dialog.transient(parent)', '')
    add_code_line(doc, 17, '        self.dialog.grab_set()', '')
    add_code_line(doc, 18, '        ', '')
    add_code_line(doc, 19, '        self.create_widgets()', '')
    add_code_line(doc, 20, '        self.refresh_list()', '')
    add_code_line(doc, 21, '        ', '')
    add_code_line(doc, 22, '        # 居中显示', '注释')
    add_code_line(doc, 23, '        self.dialog.update_idletasks()', '')
    add_code_line(doc, 24, '        x = (self.dialog.winfo_screenwidth() - self.dialog.winfo_width()) // 2', '')
    add_code_line(doc, 25, '        y = (self.dialog.winfo_screenheight() - self.dialog.winfo_height()) // 2', '')
    add_code_line(doc, 26, '        self.dialog.geometry(f\'+{x}+{y}\')', '')
    add_code_line(doc, 27, '    ', '')
    add_code_line(doc, 28, '    def create_widgets(self):', '创建组件')
    add_code_line(doc, 29, '        """创建界面组件"""', '')
    add_code_line(doc, 30, "        padding = {'padx': 10, 'pady': 5}", '')
    add_code_line(doc, 31, '        ', '')
    add_code_line(doc, 32, '        # 添加新分类区域', '注释')
    add_code_line(doc, 33, "        add_frame = ttk.LabelFrame(self.dialog, text='添加新分类', padding=10)", '带标题的框架')
    add_code_line(doc, 34, "        add_frame.pack(fill='x', padx=10, pady=5)", '')
    add_code_line(doc, 35, '        ', '')
    add_code_line(doc, 36, "        ttk.Label(add_frame, text='名称:').grid(row=0, column=0, sticky='w')", '')
    add_code_line(doc, 37, '        self.name_var = tk.StringVar()', '')
    add_code_line(doc, 38, '        self.name_entry = ttk.Entry(add_frame, textvariable=self.name_var, width=20)', '')
    add_code_line(doc, 39, '        self.name_entry.grid(row=0, column=1, padx=5)', '')
    add_code_line(doc, 40, '        ', '')
    add_code_line(doc, 41, "        self.color_var = tk.StringVar(value='#4A90D9')", '默认蓝色')
    add_code_line(doc, 42, "        self.color_btn = tk.Button(add_frame, text='选择颜色',", '颜色选择按钮')
    add_code_line(doc, 43, '                                   bg=self.color_var.get(),', '设置按钮背景色')
    add_code_line(doc, 44, '                                   command=self.choose_color)', '')
    add_code_line(doc, 45, '        self.color_btn.grid(row=0, column=2, padx=5)', '')
    add_code_line(doc, 46, '        ', '')
    add_code_line(doc, 47, "        ttk.Button(add_frame, text='添加', command=self.add_category).grid(row=0, column=3, padx=5)", '')
    
    doc.add_page_break()
    
    add_file_section(doc, 'gui/category_dialog.py - 分类列表和操作')
    
    add_code_line(doc, 49, '        # 分类列表', '注释')
    add_code_line(doc, 50, "        list_frame = ttk.LabelFrame(self.dialog, text='现有分类', padding=10)", '')
    add_code_line(doc, 51, "        list_frame.pack(fill='both', expand=True, padx=10, pady=5)", '')
    add_code_line(doc, 52, '        ', '')
    add_code_line(doc, 53, '        # Treeview', '树形表格')
    add_code_line(doc, 54, "        columns = ('name', 'color')", '')
    add_code_line(doc, 55, '        self.tree = ttk.Treeview(list_frame, columns=columns, show=\'headings\',', '')
    add_code_line(doc, 56, '                                height=8, selectmode=\'browse\')', '')
    add_code_line(doc, 57, '        ', '')
    add_code_line(doc, 58, "        self.tree.heading('name', text='名称')", '')
    add_code_line(doc, 59, "        self.tree.heading('color', text='颜色')", '')
    add_code_line(doc, 60, "        self.tree.column('name', width=150)", '')
    add_code_line(doc, 61, "        self.tree.column('color', width=100)", '')
    add_code_line(doc, 62, '        ', '')
    add_code_line(doc, 63, '        scrollbar = ttk.Scrollbar(list_frame, orient=\'vertical\', command=self.tree.yview)', '')
    add_code_line(doc, 64, '        self.tree.configure(yscrollcommand=scrollbar.set)', '')
    add_code_line(doc, 65, '        ', '')
    add_code_line(doc, 66, "        self.tree.pack(side='left', fill='both', expand=True)", '')
    add_code_line(doc, 67, "        scrollbar.pack(side='right', fill='y')", '')
    add_code_line(doc, 68, '        ', '')
    add_code_line(doc, 69, '        # 按钮区域', '注释')
    add_code_line(doc, 70, '        btn_frame = ttk.Frame(self.dialog)', '')
    add_code_line(doc, 71, "        btn_frame.pack(fill='x', padx=10, pady=5)", '')
    add_code_line(doc, 72, '        ', '')
    add_code_line(doc, 73, "        ttk.Button(btn_frame, text='删除选中', command=self.delete_category).pack(side='left', padx=5)", '')
    add_code_line(doc, 74, "        ttk.Button(btn_frame, text='关闭', command=self.dialog.destroy).pack(side='right', padx=5)", '')
    add_code_line(doc, 75, '        ', '')
    add_code_line(doc, 76, '        # 绑定双击编辑颜色', '注释')
    add_code_line(doc, 77, "        self.tree.bind('<Double-1>', self.edit_color)", '')
    add_code_line(doc, 78, '    ', '')
    add_code_line(doc, 79, '    def choose_color(self):', '选择颜色')
    add_code_line(doc, 80, '        """选择颜色"""', '')
    add_code_line(doc, 81, "        color = colorchooser.askcolor(color=self.color_var.get(), title='选择颜色')[1]", '显示颜色选择器，返回RGB和十六进制')
    add_code_line(doc, 82, '        if color:', '如果选择了颜色（不是取消）')
    add_code_line(doc, 83, '            self.color_var.set(color)', '保存颜色值')
    add_code_line(doc, 84, '            self.color_btn.configure(bg=color)', '更新按钮背景色')
    add_code_line(doc, 85, '    ', '')
    add_code_line(doc, 86, '    def add_category(self):', '添加分类')
    add_code_line(doc, 87, '        """添加分类"""', '')
    add_code_line(doc, 88, '        name = self.name_var.get().strip()', '')
    add_code_line(doc, 89, '        if not name:', '')
    add_code_line(doc, 90, "            messagebox.showerror('错误', '请输入分类名称', parent=self.dialog)", '')
    add_code_line(doc, 91, '            return', '')
    add_code_line(doc, 92, '        ', '')
    add_code_line(doc, 93, '        try:', '异常处理')
    add_code_line(doc, 94, '            self.db_manager.add_category(name, self.color_var.get())', '')
    add_code_line(doc, 95, "            self.name_var.set('')", '清空名称输入框')
    add_code_line(doc, 96, '            self.refresh_list()', '刷新列表')
    add_code_line(doc, 97, '        except Exception as e:', '捕获异常')
    add_code_line(doc, 98, "            messagebox.showerror('错误', f'添加分类失败: {e}', parent=self.dialog)", '显示错误信息')
    add_code_line(doc, 99, '    ', '')
    add_code_line(doc, 100, '    def refresh_list(self):', '刷新分类列表')
    add_code_line(doc, 101, '        """刷新分类列表"""', '')
    add_code_line(doc, 102, '        # 清空列表', '注释')
    add_code_line(doc, 103, '        for item in self.tree.get_children():', '')
    add_code_line(doc, 104, '            self.tree.delete(item)', '')
    add_code_line(doc, 105, '        ', '')
    add_code_line(doc, 106, '        # 加载分类', '注释')
    add_code_line(doc, 107, '        categories = self.db_manager.get_all_categories()', '')
    add_code_line(doc, 108, '        self.category_items = {}  # 存储 item -> id 映射', '')
    add_code_line(doc, 109, '        ', '')
    add_code_line(doc, 110, '        for cat in categories:', '')
    add_code_line(doc, 111, "            item = self.tree.insert('', 'end', values=(cat.name, ''))", '')
    add_code_line(doc, 112, '            # 在颜色列显示色块', '注释')
    add_code_line(doc, 113, "            self.tree.set(item, 'color', cat.color)", '设置颜色列的值')
    add_code_line(doc, 114, '            # 设置行颜色', '注释')
    add_code_line(doc, 115, "            self.tree.tag_configure(f'color_{cat.id}', background=cat.color)", '为每个分类创建颜色标签')
    add_code_line(doc, 116, '            self.category_items[item] = cat.id', '')
    add_code_line(doc, 117, '    ', '')
    add_code_line(doc, 118, '    def delete_category(self):', '删除分类')
    add_code_line(doc, 119, '        """删除分类"""', '')
    add_code_line(doc, 120, '        selection = self.tree.selection()', '')
    add_code_line(doc, 121, '        if not selection:', '')
    add_code_line(doc, 122, "            messagebox.showwarning('提示', '请先选择一个分类', parent=self.dialog)", '')
    add_code_line(doc, 123, '            return', '')
    add_code_line(doc, 124, '        ', '')
    add_code_line(doc, 125, '        item = selection[0]', '')
    add_code_line(doc, 126, '        category_id = self.category_items.get(item)', '')
    add_code_line(doc, 127, '        category_name = self.tree.item(item, \'values\')[0]', '')
    add_code_line(doc, 128, '        ', '')
    add_code_line(doc, 129, '        if messagebox.askyesno(\'确认\', f\'确定要删除分类 "{category_name}" 吗？\\n该分类下的任务将变为未分类。\',', '提示删除后果')
    add_code_line(doc, 130, '                              parent=self.dialog):', '')
    add_code_line(doc, 131, '            try:', '')
    add_code_line(doc, 132, '                self.db_manager.delete_category(category_id)', '')
    add_code_line(doc, 133, '                self.refresh_list()', '')
    add_code_line(doc, 134, '            except Exception as e:', '')
    add_code_line(doc, 135, "                messagebox.showerror('错误', f'删除分类失败: {e}', parent=self.dialog)", '')
    add_code_line(doc, 136, '    ', '')
    add_code_line(doc, 137, '    def edit_color(self, event):', '双击编辑颜色')
    add_code_line(doc, 138, '        """双击编辑颜色"""', '')
    add_code_line(doc, 139, '        item = self.tree.identify_row(event.y)', '')
    add_code_line(doc, 140, '        if not item:', '')
    add_code_line(doc, 141, '            return', '')
    add_code_line(doc, 142, '        ', '')
    add_code_line(doc, 143, '        category_id = self.category_items.get(item)', '')
    add_code_line(doc, 144, '        current_color = self.tree.set(item, \'color\')', '')
    add_code_line(doc, 145, '        ', '')
    add_code_line(doc, 146, "        color = colorchooser.askcolor(color=current_color, title='选择新颜色')[1]", '')
    add_code_line(doc, 147, '        if color:', '')
    add_code_line(doc, 148, '            try:', '')
    add_code_line(doc, 149, '                self.db_manager.update_category(category_id, color=color)', '只更新颜色')
    add_code_line(doc, 150, '                self.refresh_list()', '')
    add_code_line(doc, 151, '            except Exception as e:', '')
    add_code_line(doc, 152, "                messagebox.showerror('错误', f'更新颜色失败: {e}', parent=self.dialog)", '')
    add_code_line(doc, 153, '    ', '')
    add_code_line(doc, 154, '    def show(self):', '显示对话框')
    add_code_line(doc, 155, '        """显示对话框"""', '')
    add_code_line(doc, 156, '        self.parent.wait_window(self.dialog)', '')
    add_code_line(doc, 157, '', '')
    
    doc.add_page_break()
    
    # ==================== utils模块 ====================
    add_file_section(doc, 'utils/__init__.py - 工具模块')
    
    add_code_line(doc, 1, '"""工具模块"""', '模块文档字符串，当前为空模块，可扩展工具函数')
    
    doc.add_page_break()
    
    # ==================== README ====================
    add_file_section(doc, 'README.md - 项目说明文档')
    
    doc.add_paragraph('【说明】这是项目说明文档，介绍了项目功能、技术栈、使用方式等。虽然不是代码文件，但对理解项目很重要。')
    
    add_code_line(doc, 1, '# 待办清单桌面应用', 'Markdown一级标题')
    add_code_line(doc, 2, '', '')
    add_code_line(doc, 3, '> Python + tkinter + SQLite 实现的桌面待办事项管理软件', '引用块说明技术栈')
    add_code_line(doc, 4, '', '')
    add_code_line(doc, 5, '## 项目简介', '二级标题')
    add_code_line(doc, 6, '', '')
    add_code_line(doc, 7, '本项目是一个使用 Python 开发的桌面待办清单应用，采用 tkinter 构建图形界面，SQLite 进行数据持久化存储。', '')
    add_code_line(doc, 8, '', '')
    add_code_line(doc, 9, '## 功能特性', '')
    add_code_line(doc, 10, '', '')
    add_code_line(doc, 11, '- ✅ **任务管理**：添加、编辑、删除待办事项', '复选框列表项')
    add_code_line(doc, 12, '- ✅ **分类管理**：支持自定义分类，可为每个分类设置颜色标识', '')
    add_code_line(doc, 13, '- ✅ **优先级设置**：支持高、中、低三级优先级', '')
    add_code_line(doc, 14, '- ✅ **筛选搜索**：按分类、完成状态筛选，支持关键词搜索', '')
    add_code_line(doc, 15, '- ✅ **截止日期**：可为任务设置截止日期', '')
    add_code_line(doc, 16, '- ✅ **状态统计**：实时显示任务完成统计信息', '')
    add_code_line(doc, 17, '- ✅ **数据持久化**：使用 SQLite 本地存储，数据自动保存', '')
    
    # 添加总结部分
    doc.add_page_break()
    
    heading = doc.add_heading('📚 核心概念总结', level=1)
    for run in heading.runs:
        set_chinese_font(run, size=16, bold=True, color=(0, 51, 102))
    
    summary_text = '''
1. 项目架构模式
   • 采用模块化设计，将代码按功能分为config（配置）、database（数据）、gui（界面）三个包
   • 遵循MVC思想：Models定义数据结构，DBManager处理数据逻辑，GUI负责界面展示

2. 数据库设计
   • 使用SQLite轻量级数据库，单文件存储
   • 两张表：categories（分类）和todos（待办事项）
   • 外键关联：todos.category_id → categories.id，删除分类时任务变为未分类

3. GUI设计
   • 使用tkinter构建桌面界面
   • 布局采用pack和grid混合使用
   • Treeview展示任务列表，Listbox展示分类
   • 模态对话框用于添加/编辑操作

4. 关键技术点
   • @dataclass：简化数据类定义，自动生成构造方法
   • @contextmanager：自定义上下文管理器，确保资源释放
   • 参数化查询：防止SQL注入攻击
   • 列表推导式：简洁的数据转换
   • 字典推导式：快速构建映射关系

5. 常见面试问题
   Q: 为什么用__all__？
   A: 控制包对外暴露的接口，明确公共API

   Q: 什么是模态对话框？
   A: 阻塞父窗口的对话框，必须处理完才能回到主界面

   Q: 如何防止SQL注入？
   A: 使用参数化查询，用?占位符而非字符串拼接

   Q: dataclass有什么优势？
   A: 自动生成__init__、__repr__、__eq__等方法，减少样板代码
'''
    
    p = doc.add_paragraph()
    run = p.add_run(summary_text)
    set_chinese_font(run, size=10.5)
    
    # 保存文档
    output_path = '待办清单代码详解.docx'
    doc.save(output_path)
    print(f'文档已生成: {output_path}')
    return output_path


if __name__ == '__main__':
    create_explanation_doc()
